source 'https://github.com/CocoaPods/Specs.git'


platform :ios, '7.0'

target 'YTXAnimations_Example', :exclusive => true do
  pod 'YTXAnimations', :path => '../'

end

target 'YTXAnimations_Tests', :exclusive => true do
  pod 'Kiwi'

end


